In [2]:
import numpy as np

**Task 1**
Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення

In [ ]:

vector_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector_1)
vector_2 = np.arange(1, 11)
print(vector_2)


[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


**Task**
Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення

In [ ]:
matrix = np.zeros((3, 3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Task 3**
Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення

In [ ]:
matrix = np.random.randint(1, 11, (5, 5))
print(matrix)

[[ 3  9  3  3 10]
 [ 8  4  4 10  9]
 [ 7  2 10  9  7]
 [ 2  9  7  1  9]
 [ 3  3  5  5  4]]


**Task 4**
Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення

In [ ]:
matrix = np.random.random((4, 4))
print(matrix)

[[0.82525328 0.99220754 0.89333393 0.18690272]
 [0.25230493 0.60133602 0.1684687  0.34443123]
 [0.99532753 0.00858665 0.42492889 0.87745173]
 [0.99442536 0.92088407 0.72884996 0.80450304]]


**Task 5**
Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [3]:
a = np.random.randint(1, 11, (5))
b = np.random.randint(1, 11, (5))
print(a)
print(b)
print("Операція додавання:", a+b)
print("Операція віднімання:", a-b)
print("Операція множення:", a*b)

[8 6 6 8 8]
[3 4 3 2 8]
Операція додавання: [11 10  9 10 16]
Операція віднімання: [5 2 3 6 0]
Операція множення: [24 24 18 16 64]


**Task 6**
Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток

In [4]:
vector_a = np.random.randint(1, 101, 7)
vector_b = np.random.randint(1, 101, 7)
print(vector_a)
print(vector_b)
scalar = np.dot(vector_a, vector_b)
print(scalar)


[44 95 45  6 21  9 98]
[21  8 32 90 70 93 50]
10871


**Task 7**
Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [6]:
matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))
print(matrix_1)
print(matrix_2)
result = np.dot(matrix_1, matrix_2)
print(result)

[[ 2 10]
 [ 3  8]]
[[ 8  6 10]
 [ 5  8  9]]
[[ 66  92 110]
 [ 64  82 102]]


**Task 8**
Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [7]:
matrix = np.random.randint(1, 11, (3, 3))
print("Матриця початкова")
print(matrix)
inverse_matrix = np.linalg.inv(matrix)
print("Матриця обернена")
print(inverse_matrix)


Матриця початкова
[[7 4 6]
 [8 8 7]
 [8 2 3]]
Матриця обернена
[[-1.11111111e-01  5.55111512e-17  2.22222222e-01]
 [-3.55555556e-01  3.00000000e-01  1.11111111e-02]
 [ 5.33333333e-01 -2.00000000e-01 -2.66666667e-01]]


**Task 9**
Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [8]:
matrix = np.random.random((4, 4))
print("Матриця початкова")
print(matrix)
trans_matrix = matrix.T
print("Матриця транспонована")
print(trans_matrix)


Матриця початкова
[[0.42229498 0.42786826 0.4163139  0.0104417 ]
 [0.31305647 0.03043989 0.73192904 0.77810622]
 [0.83794894 0.76062852 0.25197166 0.24221212]
 [0.60444612 0.33030487 0.25067882 0.81159005]]
Матриця транспонована
[[0.42229498 0.31305647 0.83794894 0.60444612]
 [0.42786826 0.03043989 0.76062852 0.33030487]
 [0.4163139  0.73192904 0.25197166 0.25067882]
 [0.0104417  0.77810622 0.24221212 0.81159005]]


**Task 10**
Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор

In [9]:
matrix = np.random.randint(1, 11, (3, 4))
print("Matrix:")
print(matrix)
vector = np.random.randint(1, 11, 4)
print("Vector:")
print(vector)
result = matrix * vector
print("Добуток матриці на вектор:")
print(result)


Matrix:
[[ 7  8  4  2]
 [ 9  5 10  4]
 [ 3  2  3  2]]
Vector:
[9 2 9 7]
Добуток матриці на вектор:
[[63 16 36 14]
 [81 10 90 28]
 [27  4 27 14]]


**Task 11**
Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [10]:
matrix = np.random.random((2, 3))
print("Matrix:")
print(matrix)
vector = np.random.random((3))
print("Vector:")
print(vector)
result = matrix * vector
print("Добуток матриці на вектор:")
print(result)

Matrix:
[[0.13561629 0.81974265 0.61585886]
 [0.59951459 0.23902709 0.92091028]]
Vector:
[0.37827642 0.95202542 0.17205559]
Добуток матриці на вектор:
[[0.05130044 0.78041584 0.10596196]
 [0.22678223 0.22755986 0.15844776]]


**Task 12**
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
matrix_1 = np.random.randint(1, 11, (2, 2))
print("Перша матриця:")
print(matrix_1)
matrix_2 = np.random.randint(1, 11, (2, 2))
print("Друга матриця:")
print(matrix_2)
result = matrix_1 * matrix_2
print("Добуток двох матриць:")
print(result)

Перша матриця:
[[10 10]
 [ 6  4]]
Друга матриця:
[[5 1]
 [3 8]]
Добуток двох матриць:
[[50 10]
 [18 32]]


**Task 13**
Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
matrix_1 = np.random.randint(1, 11, (2, 2))
print("Перша матриця:")
print(matrix_1)
matrix_2 = np.random.randint(1, 11, (2, 2))
print("Друга матриця:")
print(matrix_2)
result = np.dot(matrix_1 , matrix_2)
print("Добуток двох матриць:")
print(result)

Перша матриця:
[[5 1]
 [8 8]]
Друга матриця:
[[9 6]
 [9 2]]
Добуток двох матриць:
[[ 54  32]
 [144  64]]


**Task 14**
Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
matrix = np.random.randint(1, 101, (5, 5))
print(" матриця:")
print(matrix)

result = np.sum(matrix)
print("Сума елементів матриці:")
print(result)

 матриця:
[[47 56 35 62 99]
 [55 52 37 45 66]
 [ 7 64 91 64 84]
 [71 95 93 87 49]
 [51 71 52 36 50]]
Сума елементів матриці:
1519


**Task 15**
Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
matrix_1 = np.random.randint(1, 11, (4, 4))
print("Перша матриця:")
print(matrix_1)
matrix_2 = np.random.randint(1, 11, (4, 4))
print("Друга матриця:")
print(matrix_2)
result = matrix_1 - matrix_2
print("Різниця двох матриць:")
print(result)

Перша матриця:
[[10  2  8  3]
 [10  5  9 10]
 [10  6  5  3]
 [ 2  1  2  9]]
Друга матриця:
[[ 1  3  1  1]
 [ 8 10  8  9]
 [ 6  1  8  9]
 [ 4  4  6  1]]
Різниця двох матриць:
[[ 9 -1  7  2]
 [ 2 -5  1  1]
 [ 4  5 -3 -6]
 [-2 -3 -4  8]]


**Task 16**
Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [24]:
matrix = np.random.random((3, 3))
print("Matrix:")
print(matrix)
print("Перше число вектора - сума першого рядка матриці:")
num_one = np.sum(matrix[0])
print(num_one)
print("Друге число вектора - сума другого рядка матриці:")
num_two = np.sum(matrix[1])
print(num_two)
print("Третє  число вектора - сума третього рядка матриці:")
num_three = np.sum(matrix[2])
print(num_three)
vector = np.array([num_one, num_two, num_three]).reshape(3, 1)
print("Вектор-стовпчик:")
print(vector)

Matrix:
[[0.01903909 0.17213585 0.41878392]
 [0.34879018 0.57788642 0.83638931]
 [0.92969829 0.10813051 0.57829897]]
Перше число вектора - сума першого рядка матриці:
0.6099588654623572
Друге число вектора - сума другого рядка матриці:
1.7630659240525528
Третє  число вектора - сума третього рядка матриці:
1.6161277705832637
Вектор-стовпчик:
[[0.60995887]
 [1.76306592]
 [1.61612777]]


**Task 17**
Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [25]:
matrix = np.random.randint(1, 11, (3, 4))
print("Матриця:")
print(matrix)
sqr_matrix = np.square(matrix)
print("Матриця з квадратів чисел:")
print(sqr_matrix)

Матриця:
[[5 3 2 8]
 [1 8 7 8]
 [2 3 4 2]]
Матриця з квадратів чисел:
[[25  9  4 64]
 [ 1 64 49 64]
 [ 4  9 16  4]]


**Task 18**
Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [26]:
vector = np.random.randint(1, 51, (4))
print("Початковий вектор:")
print(vector)
sqrt_vector = np.sqrt(vector)
print("Вектор з коренів чисел:")
print(sqrt_vector)

Початковий вектор:
[35 31  5 49]
Вектор з коренів чисел:
[5.91607978 5.56776436 2.23606798 7.        ]
